### ISSUE TITLE
It doesn't actually work

### ISSUE THREAD

**Issue by kgsensei** [Runabox/blooket-answer-finder#1]
I like the idea of a Blooket answer finder a lot, the only issue is that this project doesn't work yet.
I know a bit about web development and I just finished my own Blooket project so I was wondering if you want some help building this.

Oh, and this isn't actually an issue so feel free to close this.

Thanks for your time.

**Comment by Runabox** [comment]
https://blooket.runa.live is the current live version. By Game Code I mean the Game ID sorry I should have made it say Game ID not code. You can find the Game ID by monitoring network requests when you connect to the game. Blooket should make a post request to their API getting the game information and you can find it there.

**Comment by kgsensei** [comment]
Cool. Looks good.
